# Generated by Django 5.2.1 on 2025-05-26 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardim', '0005_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='help_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='yardim.helprequest'),
        ),
    ]
