# Generated by Django 5.2.1 on 2025-05-26 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardim', '0006_message_help_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='help_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='yardim.helprequest'),
        ),
    ]
