# Generated by Django 5.2.1 on 2025-05-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yardim', '0007_alter_message_help_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='help_request',
        ),
    ]
